package lk.ijse.service.custom.impl;

import lk.ijse.dao.DAOFactory;
import lk.ijse.dao.custom.CustomerDAO;
import lk.ijse.dto.CustomerDTO;
import lk.ijse.entity.Customer;
import lk.ijse.service.custom.CustomerService;

import java.util.ArrayList;
import java.util.List;

public class CustomerServiceImpl implements CustomerService {

    private final CustomerDAO customerDAO =
            (CustomerDAO) DAOFactory.getInstance().getDAO(DAOFactory.DAOTypes.CUSTOMER);

    @Override
    public boolean addCustomer(CustomerDTO dto) throws Exception {

        Customer customer = new Customer(
                dto.getCustomerId(),
                dto.getName(),
                dto.getNicPassport(),
                dto.getContactNo(),
                dto.getEmail(),
                dto.getAddress(),
                dto.getMembership(),
                null            // createdAt generated by DB
        );

        return customerDAO.save(customer);
    }

    @Override
    public boolean updateCustomer(CustomerDTO dto) throws Exception {

        Customer customer = new Customer(
                dto.getCustomerId(),
                dto.getName(),
                dto.getNicPassport(),
                dto.getContactNo(),
                dto.getEmail(),
                dto.getAddress(),
                dto.getMembership(),
                dto.getCreatedAt()     // keep existing timestamp
        );

        return customerDAO.update(customer);
    }

    @Override
    public boolean deleteCustomer(long id) throws Exception {
        return customerDAO.delete(id);
    }

    @Override
    public CustomerDTO findCustomer(long id) throws Exception {

        Customer c = customerDAO.find(id);
        if (c == null) return null;

        return new CustomerDTO(
                c.getCustomerId(),
                c.getName(),
                c.getNicPassport(),
                c.getContactNo(),
                c.getEmail(),
                c.getAddress(),
                c.getMembership(),
                c.getCreatedAt()
        );
    }

    @Override
    public List<CustomerDTO> getAllCustomers() throws Exception {

        List<Customer> list = customerDAO.findAll();
        List<CustomerDTO> dtoList = new ArrayList<>();

        for (Customer c : list) {
            dtoList.add(
                    new CustomerDTO(
                            c.getCustomerId(),
                            c.getName(),
                            c.getNicPassport(),
                            c.getContactNo(),
                            c.getEmail(),
                            c.getAddress(),
                            c.getMembership(),
                            c.getCreatedAt()
                    )
            );
        }

        return dtoList;
    }
}